version: '2'
services:
    gj-app:
        image: gj
        external_links:
            - gj-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gj?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gj-mysql:
        extends:
            file: mysql.yml
            service: gj-mysql
